// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdSZuvSSxo8X9-3u-kGeXwze1JcXSZe2w',
    appId: '1:120090476985:web:fc624477af4f42fa26f668',
    messagingSenderId: '120090476985',
    projectId: 'kurumzili',
    authDomain: 'kurumzili.firebaseapp.com',
    storageBucket: 'kurumzili.firebasestorage.app',
    measurementId: 'G-2D65L2MY9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrTw7PEOdC_1gRPpykHYlq-LttvcW-7EM',
    appId: '1:120090476985:android:b28716a0b90dc8e226f668',
    messagingSenderId: '120090476985',
    projectId: 'kurumzili',
    storageBucket: 'kurumzili.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFOqt2DE5vjsP0NlTJMBIdBPTXVCip2rg',
    appId: '1:120090476985:ios:50816084cf99ee4f26f668',
    messagingSenderId: '120090476985',
    projectId: 'kurumzili',
    storageBucket: 'kurumzili.firebasestorage.app',
    iosBundleId: 'com.example.kurumzili',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFOqt2DE5vjsP0NlTJMBIdBPTXVCip2rg',
    appId: '1:120090476985:ios:50816084cf99ee4f26f668',
    messagingSenderId: '120090476985',
    projectId: 'kurumzili',
    storageBucket: 'kurumzili.firebasestorage.app',
    iosBundleId: 'com.example.kurumzili',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdSZuvSSxo8X9-3u-kGeXwze1JcXSZe2w',
    appId: '1:120090476985:web:6f6c1b88673f251c26f668',
    messagingSenderId: '120090476985',
    projectId: 'kurumzili',
    authDomain: 'kurumzili.firebaseapp.com',
    storageBucket: 'kurumzili.firebasestorage.app',
    measurementId: 'G-DJP28G4BC6',
  );
}
